version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@sentry/tracing"
    versions:
    - 6.0.2
    - 6.0.3
    - 6.0.4
    - 6.1.0
    - 6.2.0
    - 6.2.1
    - 6.2.2
    - 6.2.5
    - 6.3.0
    - 6.3.1
  - dependency-name: postcss
    versions:
    - 8.2.10
    - 8.2.12
    - 8.2.7
  - dependency-name: concurrently
    versions:
    - 6.0.1
  - dependency-name: rollup
    versions:
    - 2.38.1
    - 2.38.2
    - 2.38.3
    - 2.38.4
    - 2.38.5
    - 2.39.0
    - 2.39.1
    - 2.42.2
    - 2.42.3
    - 2.42.4
    - 2.43.1
    - 2.44.0
    - 2.45.0
    - 2.45.1
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@sentry/browser"
    versions:
    - 6.0.2
    - 6.0.3
    - 6.0.4
    - 6.1.0
    - 6.2.0
    - 6.2.1
    - 6.2.3
    - 6.2.4
  - dependency-name: "@babel/core"
    versions:
    - 7.13.10
    - 7.13.13
    - 7.13.14
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.10
    - 7.13.12
    - 7.13.9
  - dependency-name: postcss-import
    versions:
    - 14.0.0
  - dependency-name: "@babel/plugin-transform-runtime"
    versions:
    - 7.13.9
  - dependency-name: "@babel/runtime"
    versions:
    - 7.13.9
  - dependency-name: autoprefixer
    versions:
    - 10.2.3
    - 10.2.4
  - dependency-name: "@rollup/plugin-node-resolve"
    versions:
    - 11.1.0
    - 11.1.1
    - 11.2.0
  - dependency-name: "@rollup/plugin-babel"
    versions:
    - 5.2.3
    - 5.3.0
  - dependency-name: parcel-plugin-static-files-copy
    versions:
    - 2.5.1
  - dependency-name: preact
    versions:
    - 10.5.12
